### ISSUE TITLE
docker logs input

### ISSUE THREAD

**Issue by vanodevium** [NarrativeScience/log.io#264]
Hello!

How do you like the idea of making an input that will read docker container logs using a docker socket?

It could be taken out into a separate package (like `log.io-docker-input`) and there was no need to configure separate inputs, but simply see a list of all containers and logs in them.

Next is docker-compose example:

```yml
  log.io:
    build:
      context: ./docker/log.io
    restart: unless-stopped
    container_name: log.io
    user: "1000:1000"
    ports:
      - "6688:6688"
      - "6689:6689"
    command: "log.io-server"
    
  log.io-docker-input:
    build:
      context: ./docker/log.io-docker-input
    restart: unless-stopped
    container_name: log.io-docker-input
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "log.io-docker-input --server=log.io:6689"
```
